### ISSUE TITLE
[License] Switch to AGPL?

### ISSUE THREAD

**Issue by realaravinth** [AaronErhardt/Triox#15]
Please consider switching to AGPL. GPL is a cool license but wasn't designed in network-enabled software in mind. That's the only difference between GPL and AGPL.

## Resources:
- https://www.gnu.org/licenses/why-affero-gpl.en.html
- https://plausible.io/blog/open-source-licenses#what-is-the-gnu-gplv3-license

**Comment by AaronErhardt** [comment]
Makes sense to me. Didn't know about this "loophole" in the standard GPL, so thanks for pointing it out :+1:
